# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hailo-examples-phytec"
BBFILE_PATTERN_hailo-examples-phytec = "^${LAYERDIR}/"
BBFILE_PRIORITY_hailo-examples-phytec = "8"

LAYERDEPENDS_hailo-examples-phytec = "core"
LAYERSERIES_COMPAT_hailo-examples-phytec = "scarthgap"