#!/usr/bin/env python3
"""YOLOv8n object detection on a video file: Hailo-8 vs i.MX8MP CPU, side by side."""

import sys

from object_detect.camera_cli import run

sys.exit(run("compare", require_source=True))
